CREATE DATABASE QUANLYTHUVIEN
USE QUANLYTHUVIEN
CREATE TABLE QUANLY(
	MAQL VARCHAR(20) PRIMARY KEY, TENQL NVARCHAR(50), NGAYSINH CHAR(20), DIACHI NVARCHAR(50), SDT CHAR(20)  
)
select * from QUANLY
INSERT INTO QUANLY VALUES('QL001', N'TRẦN QUANG MINH', '29/09/2003', N'HÀ NỘI', '0352593469')
CREATE TABLE SINHVIEN(
	MASV VARCHAR(20) PRIMARY KEY, TENSV NVARCHAR(50), NGAYSINH CHAR(20), DIACHI NVARCHAR(50), SDT CHAR (10), LOP CHAR(20), TIEN float)
INSERT INTO SINHVIEN VALUES('SV001', N'NGUYỄN XUÂN MANH', '29/03/2003', N'BA VÌ HÀ NỘI', '0352593455', 'DCCNTT12.10.3', 10.5);
select * from SINHVIEN
CREATE TABLE QLSV(
	MAQL VARCHAR(20) FOREIGN KEY REFERENCES QUANLY(MAQL) ,
	MASV VARCHAR (20) FOREIGN KEY REFERENCES SINHVIEN(MASV),
	PRIMARY KEY (MAQL, MASV)
)
-- BẢN MƯỢN
CREATE TABLE SACH (
	MASACH VARCHAR(20) PRIMARY KEY, TENSACH NVARCHAR(50), SOTIEN FLOAT, LOAISACH NVARCHAR(50)
)
INSERT INTO SACH VALUES('', N'', 1,N'')
-- LIÊN KẾT VỚI SINH VIÊN
CREATE TABLE MUON (
	MASV VARCHAR(20) FOREIGN KEY REFERENCES SINHVIEN(MASV),
	MASACH VARCHAR (20)FOREIGN KEY REFERENCES SACH(MASACH),
	NGAYMUON VARCHAR(30)
	PRIMARY KEY (MASV, MASACH)
)
--LIÊN KẾT QUẢN LÝ VỚI SÁCH
CREATE TABLE QLSACH (
	MASACH VARCHAR(20) FOREIGN KEY REFERENCES SACH(MASACH),
	MAQL VARCHAR(20) FOREIGN KEY REFERENCES QUANLY (MAQL)
	PRIMARY KEY (MASACH, MAQL)
)
-- TÀI KHOẢN
CREATE TABLE TAIKHOAN(
	MATK VARCHAR(20) PRIMARY KEY, TENTK NVARCHAR(50), MATKHAU CHAR(20), MASV VARCHAR(20) FOREIGN KEY REFERENCES SINHVIEN(MASV) 
)
insert into TAIKHOAN values ('TK001', 'XUANMANH9999', '123', 'SV001')
-- QLTK 
CREATE TABLE QLTK (
	MATK VARCHAR(20) FOREIGN KEY REFERENCES TAIKHOAN(MATK),
	MAQL VARCHAR (20) FOREIGN KEY REFERENCES QUANLY(MAQL)
)
-----------------------------------------------------------ĐOẠN TRUY VẤN--------------------------------------------------
select MATK from TAIKHOAN
insert into TAIKHOAN values ('TK002', 'Nguyễn Xuân Mạnh', '', '')
select * from SINHVIEN
INSERT INTO SINHVIEN VALUES('SV001', N'NGUYỄN XUÂN MANH', '29/03/2003', N'BA VÌ HÀ NỘI', '0352593455', 'DCCNTT12.10.3', 10.5);
select MATKHAU from TAIKHOAN where MASV = 20210794
--Thêm Sách
insert into SACH values('MS001', N'Đắc Nhân Tâm', 150000, N'Phát Triển Cá Nhân')
insert into SACH values('MS002', N'Bí Mật Tư Duy Triệu Phú', 120000, N'Phát Triển Cá Nhân')
insert into SACH values('MS004', N'Đừng Bao Giờ Đi Ăn Một Mình', 125000, N'Phát Triển Cá Nhân')
insert into SACH values('MS003', N'Lập Trình C, C++', 100000, N'Lập Trình')
insert into SACH values('MS006', N'Lập Trình Java', 100000, N'Lập Trình')
insert into SACH values('MS005', N'Lập Trình Python', 100000, N'Lập Trình')
select * from SACH where LOAISACH = N'Phát Triển Cá Nhân'
select DISTINCT LOAISACH from SACH 
select * from MUON
select * from SACH
select * from SACH where TENSACH like '%  Ca %'
select * from TAIKHOAN
select * from MUON
--Nhập Mượn
insert into MUON values ('20210794', 'MS001', '20033920')
select SACH.MASACH, TENSACH, SOTIEN, LOAISACH, NGAYMUON, MASV from SACH, MUON where SACH.MASACH = MUON.MASACH and MUON.MASV = (select MASV from TAIKHOAN where TAIKHOAN.TENTK = 'XuanManh9999')
select * from MUON
delete from MUON where MASV = '20210794' and MASACH = 'ms001'
select MASV, TENSV, TIEN from SINHVIEN where MASV = '20210794'
update SINHVIEN set TIEN = 10000000 where MASV = '20210794'
update SINHVIEN set TIEN -= 1000 where MASV = '20210794'
select * from SACH, MUON, SINHVIEN where MUON.MASV = SINHVIEN.MASV and MUON.MASV = '20210794'
select TENSACH, SOTIEN from SACH, MUON where SACH.MASACH = MUON.MASACH and MUON.MASV = (select MASV from TAIKHOAN where TAIKHOAN.TENTK = 'XuanManh9999')
select * from TAIKHOAN
update TAIKHOAN set MATK = 'TK00537', TENTK = N'Manh', MATKHAU = '123', MASV = '20210858' where MATK = 'TK00537'
delete from TAIKHOAN where MATK = 'TK00537'
select * from TAIKHOAN where TENTK like '%d%' or MASV like '%1%'
select DISTINCT SINHVIEN.MASV, SINHVIEN.TENSV, SINHVIEN.SDT,  SINHVIEN.LOP, SACH.TENSACH, MUON.NGAYMUON from SINHVIEN, SACH, MUON where SINHVIEN.MASV = MUON.MASV and SACH.MASACH = MUON.MASACH